[build]
  publish = "dist"
  command = "build.bat"

[build.environment]
  NODE_VERSION = "18"

# Form notifications - Email all form submissions to exrevolution8@gmail.com
[context.production.environment]
  FORM_NOTIFICATION_EMAIL = "exrevolution8@gmail.com"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Admin panel security
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Admin redirects
[[redirects]]
  from = "/admin"
  to = "/admin/login.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/login.html"
  status = 200

# Main site redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/case-studies"
  to = "/case-studies.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
